language: node_js
sudo: required
dist: trusty
node_js:
  - stable 
services:
  - postgresql
addons:
  postgresql: “9.4"
before_install:
  - npm install sequelize-cli -g
before_script:
  - psql -c ‘drop database if exists database_test;’ -U postgres
  - psql -c 'create databse database_test;' -U postgres
  - psql -c 'CREATE USER juliemugira;' -U postgres
  - NODE_ENV=test
before_success:
- npm test
after_success:
- npm run coveralls