language: node_js
sudo: false
node_js:
  - stable
  
services:

cache:
  directories:
    - node_modules

before_success:
- npm run travis:test
# - npm run test:server

after_success:
- npm run coveralls