language: node_js
sudo: required  
dist: trusty
node_js:
  - stable
services:
  - postgresql
addons:
  postgresql: “9.4"
before_install:
  - npm install sequelize-cli -g
before_script:
  - psql -c "CREATE DATABASE database_test;" -U postgres
  - psql -c “CREATE USER juliemugira;” -U postgres
  - NODE_ENV=test
script:
  - npm test
after_script:
  - npm run coveralls