language: node_js
sudo: required  
dist: trusty
node_js:
  - stable
services:
  - postgresql
addons:
  postgresql: "9.6"
before_install:
  - npm install sequelize-cli -g
before_script:
  - psql -c "drop database if exists database_test;" -U postgres
  - psql -c "create database database_test;" -U postgres
  - psql -c "CREATE USER juliemugira;" -U postgres
  - NODE_ENV=test
script:
  - npm test
after_script: 
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage